### ISSUE TITLE
table.where(whereclause).read() doesn't work on minified version

### ISSUE THREAD

**Issue by aline-almeida** [Azure/azure-mobile-apps-js-client#249]
When trying to filter data on server with a where clause, it returns "unsupported expression null", if using the minified version of the SDK. 
If we change to the standard version, it returns the correct data.

**Comment by adrianhall** [comment]
What whereclause causes the issue?  Would rather have a known reproducible case to work from.  

I just set up a quick repro, and a basic where clause works fine, using .where({ completed: true })

**Comment by aline-almeida** [comment]
having a field named authId in my table, I'm using:
.where({ authId: 'some string' })

**Comment by adrianhall** [comment]
Just re-reading your report.  Is this in the Node.js server code (i.e. a table controller in the /tables directory on the server) or on the JavaScript client?  

What else can you tell us about the client?  Are you using a specific framework?  What browser are you using?

**Comment by aline-almeida** [comment]
Hi!
It's in the JavaScript client. I'm integrating an azure mobile app .net backend with an MVC AngularJS app - following your zumo book :)
I've tried with Edge, IE, Chrome & Firefox. All return the same error.

**Comment by adrianhall** [comment]
Thanks - I'll try and reproduce and revert back.

**Comment by danderson00** [comment]
There is definitely a regression here. We'll investigate further and get back to you!

**Comment by danderson00** [comment]
I can confirm there is a bug here with the minified bundle to do with variable name mangling. You have a couple of options here - use the non-minified bundle, or build a custom bundle. I intend to check in a change to the minification configuration that disables variable name mangling for now - once this is done you can follow the steps in the readme to build the bundle.

**Comment by danderson00** [comment]
FYI, made this [commit](https://github.com/Azure/azure-mobile-apps-js-client/commit/648df3704669452f18471ae22026adf2b0813768) that disables mangling. Building the bundle manually should resolve this issue. We will do another release shortly.

**Comment by danderson00** [comment]
Hi @aline-almeida, we just published version 2.0.1 that resolves this issue. There is no change except for the minified bundle. 

Thanks for reporting this! Please let us know if you have any other issues!

**Comment by aline-almeida** [comment]
Hi @danderson00 !
I can confirm it's working now.
Thanks.

**Comment by shah-smit** [comment]
@aline-almeida I am still having the issue when i am using it in Angular4 project.

**Comment by kraiz** [comment]
I would call the issue is resolved. If you install the NPM package you usually have a build mechanism that does a minification step. Everyone doing this will run into this problem again.
